RADALogisticsWEB/Models/DetailsTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RADALogisticsWEB.Models
{
    public class DetailsTable
    {
        public string id { get; set; }
        public string Folio { get; set; }
        public string Type_Status { get; set; }
        public string GruaMov { get; set; }
        public string ProcessMovement { get; set; }
        public string End_date { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string Date_Process { get; set; }
    }
}

RADALogisticsWEB/Controllers/RADAController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RADALogisticsWEB.Models;

namespace RADALogisticsWEB.Controllers
{
    public class RADAController : Controller
    {
        List<Usuarios> GetChoffer = new List<Usuarios>();

        List<Historial> GetRecords = new List<Historial>();

        List<Historial> GetRecordsQuery = new List<Historial>();

        List<Inventario> GetInventary = new List<Inventario>();

        List<Movement> Movements = new List<Movement>();

        List<UsuarioRada> UsuarioRadasss = new List<UsuarioRada>();

        List<string> filtroAreas = new List<string>();
        List<Areas> getAreas = new List<Areas>();

        //connection SQL server (database)
        SqlConnection DBSPP = new SqlConnection("Data Source=RADAEmpire.mssql.somee.com ;Initial Catalog=RADAEmpire ;User ID=RooRada; password=rada1311");
        SqlCommand con = new SqlCommand();
        SqlDataReader dr;
        // GET: RADA


        [HttpGet]
        public JsonResult GetGruaRequest(string area)
        {
            string validation = null;
            using (SqlConnection conn = new SqlConnection("Data Source=RADAEmpire.mssql.somee.com ;Initial Catalog=RADAEmpire ;User ID=RooRada; password=rada1311"))
            {
                SqlCommand cmd = new SqlCommand("SELECT GruaRequest FROM RADAEmpire_AAreas WHERE Active = '1' AND Name = @Area", conn);
                cmd.Parameters.AddWithValue("@Area", area);
                conn.Open();
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        validation = reader[0].ToString();
                    }
                }
            }

            return Json(new { gruaRequest = validation }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Changes(string ID, string oldArea, string Area, string Type, string ActivoRampa, string Container,string ActivoHidden) 
        {
            // Intentar recuperar Username desde la cookie si está nulo
            if (Session["Username"] == null && Request.Cookies["UserCookie"] != null)
            {
                Session["Username"] = Request.Cookies["UserCookie"].Value;
            }

            // Intentar recuperar Type desde la cookie si está nulo
            if (Session["Type"] == null && Request.Cookies["TypeCookie"] != null)
            {
                Session["Type"] = Request.Cookies["TypeCookie"].Value;
            }

            // Validación final: si sigue sin Username o Type, redirigir al login
            if (Session["Username"] == null || Session["Type"] == null)
            {
                return RedirectToAction("LogIn", "Login");
            }
            else
            {
                ViewBag.User = Session["Username"];
            ViewBag.Type = Session["Type"];
                using (SqlConnection conn = new SqlConnection("Data Source=RADAEmpire.mssql.somee.com ;Initial Catalog=RADAEmpire ;User ID=RooRada; password=rada1311"))
                {
                    conn.Open();
                    //Delete process
                    string deleteQuery = @"DELETE FROM [RADAEmpire].[dbo].[RADAEmpires_DZDetailsHisense]
                           WHERE Folio = @Folio";

                    using (SqlCommand cmd = new SqlCommand(deleteQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@Folio", "MOV1658");
                        int rowsAffected = cmd.ExecuteNonQuery();
                    }
                    conn.Close();

                    List<string> lista = new List<string>();

                    conn.Open();
                    // Obtener lista de pasos
                    using (SqlCommand cmd = new SqlCommand("SELECT * FROM RADAEmpire_AAreasAsign WHERE Active = 1 AND Status = @Status AND AreaAssign = @AreaAssign AND GruaRequest = @GruaRequest AND RaR = @RaR ORDER BY NumberOrder ASC", conn))
                    {
                        cmd.Parameters.AddWithValue("@Status", Type);
                        cmd.Parameters.AddWithValue("@AreaAssign", Area);
                        cmd.Parameters.AddWithValue("@GruaRequest", ActivoHidden);
                        cmd.Parameters.AddWithValue("@RaR", ActivoRampa);

                        using (SqlDataReader reader = cmd.ExecuteReader())
                        {
                            if (!reader.HasRows)
                                return RedirectToAction("RequestContainer", "HISENSE");

                            while (reader.Read())
                            {
                                lista.Add(reader["Message"].ToString()); // Puedes cambiar reader[0] por reader["NombreCampo"]
                            }
                        }
                    }
                    conn.Close();
                    ViewBag.ID = ID;

                    // Obtener hora en US (Rosarito - Pacific Time)
                    TimeZoneInfo usTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
                    DateTime usTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, usTimeZone);
                    string dateOnly = usTime.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
                    string timeOnly = usTime.ToString("HH:mm:ss");

                    //query message ------------------------------------------------------------------------------------------------------------------
                    string updateQuery = "UPDATE RADAEmpire_BRequestContainers SET shift = @shift WHERE Folio = @ID";
                    using (SqlCommand command = new SqlCommand(updateQuery, DBSPP))
                    {
                        DBSPP.Open();
                        command.Parameters.AddWithValue("@shift", Area.ToUpper());
                        command.Parameters.AddWithValue("@ID", ID.ToString());
                        int rowsAffected = command.ExecuteNonQuery();
                        DBSPP.Close();
                    }

                    //    // Insertar en RADAEmpire_BRequestContainers
                    //    using (SqlCommand insertReq = new SqlCommand(@"INSERT INTO RADAEmpire_BRequestContainers 
                    //(Placa,Urgencia, Folio, Who_Send, Container, Destination_Location, Origins_Location, Status, message, shift, Date, Datetime, Active, GruaRequest, RaRRequest)
                    //VALUES (@Placa,@Urgencia, @Folio, @Who_Send, @Container, @Destination_Location, @Origins_Location, @Status, @message, @shift, @Date, @Datetime, @Active, @GruaRequest, @RaRRequest)", conn))
                    //    {
                    //        insertReq.Parameters.AddWithValue("@Urgencia", NivelUrgencia.ToString());
                    //        insertReq.Parameters.AddWithValue("@Placa", Placa?.ToString() ?? "NO SE REGISTRO");
                    //        insertReq.Parameters.AddWithValue("@Folio", Folio);
                    //        insertReq.Parameters.AddWithValue("@Who_Send", User);
                    //        insertReq.Parameters.AddWithValue("@Container", Container.ToUpper());
                    //        insertReq.Parameters.AddWithValue("@Destination_Location", Destination.ToUpper());
                    //        insertReq.Parameters.AddWithValue("@Origins_Location", Origins.ToUpper());
                    //        insertReq.Parameters.AddWithValue("@Status", Type);
                    //        insertReq.Parameters.AddWithValue("@message", "PENDING");
                    //        insertReq.Parameters.AddWithValue("@shift", Area);
                    //        insertReq.Parameters.AddWithValue("@Date", dateOnly);
                    //        insertReq.Parameters.AddWithValue("@Datetime", timeOnly);
                    //        insertReq.Parameters.AddWithValue("@Active", true);
                    //        insertReq.Parameters.AddWithValue("@GruaRequest", ActivoHidden);
                    //        insertReq.Parameters.AddWithValue("@RaRRequest", ActivoRampa);

                    //        insertReq.ExecuteNonQuery();
                    //    }

                    //// Insertar en RADAEmpire_BRequestContainers
                    //using (SqlCommand insertReq = new SqlCommand(@"INSERT INTO RADAERmpire_AMessagesUrgent 
                    // (Folio,Status,Description,Active,Dateadded,DateTimeadded)
                    //   VALUES 
                    // (@Folio,@Status,@Description,@Active,@Dateadded,@DateTimeadded)", conn))
                    //{
                    //    insertReq.Parameters.AddWithValue("@Folio", Folio.ToString());
                    //    insertReq.Parameters.AddWithValue("@Status", NivelUrgencia.ToString());
                    //    insertReq.Parameters.AddWithValue("@Description", MotivoUrgencia.ToUpper());
                    //    insertReq.Parameters.AddWithValue("@Active", true);
                    //    insertReq.Parameters.AddWithValue("@Dateadded", usTime.ToString());
                    //    insertReq.Parameters.AddWithValue("@DateTimeadded", usTime.ToString());

                    //    insertReq.ExecuteNonQuery();
                    //}

                    //    // Insertar en RADAEmpire_CEntryContrainers
                    //    using (SqlCommand insertEntry = new SqlCommand(@"INSERT INTO RADAEmpire_CEntryContrainers
                    //(Folio_Request, Username, Time_Confirm, Choffer, FastCard, Time_Finished, Date, AreaWork, Active, Cancel)
                    //VALUES (@Folio_Request, @Username, @Time_Confirm, @Choffer, @FastCard, @Time_Finished, @Date, @AreaWork, @Active, @Cancel)", conn))
                    //    {
                    //        insertEntry.Parameters.AddWithValue("@Folio_Request", Folio);

RADALogisticsWEB/Views/HISENSE/CancelContainer.cshtml
@{
    ViewBag.Title = "RADA Logistics | Remove";
}

<link href="~/Stylee/HisensePages.css" rel="stylesheet" />

<div class="container" style="text-align: center; width: 100%">

    <div style="text-align: center; min-width: 100%; ">

        <p style="text-align: center;">&nbsp;</p>

        <h4 class="labelTitt" style="font-size:24px"> ❌ Remove Container Movement </h4>
        <h5 style="text-align: center; font-size: 16px"> Enter the reason why you are removing the Movement </h5>

        <hr>
        <div style=" display: flex; justify-content: center; align-items: center; height: auto;">

            <button class="animated-button" onclick="location.href='@Url.Action("RequestContainer","HISENSE")'">
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-2" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
                <span class="text">Return to back</span>
                <span class="circle"></span>
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-1" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
            </button>

        </div>
        <hr>

       @using (Html.BeginForm("Delete", "HISENSE", FormMethod.Post))
        {
            <input id="ID" name="ID" value="@ViewBag.ID" hidden="hidden" style="text-align:center" />

            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>

            <div class="group">

                <input type="text" id="Reason" name="Reason" style=" font-size: 15px" required>

                <span class="highlight"></span>
                <span class="bar"></span>
                <label>Reason Remove:</label>

            </div>

            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>

            <button type="submit" class="Bto_saved">
                📍 Remove
            </button>

        }
    </div>

</div>

RADALogisticsWEB/Views/HISENSE/ChangeStatus.cshtml
@{
    ViewBag.Title = "RADA Logistics | Change";
    var pageValue = ViewBag.Page ?? "";
    var data = ViewBag.data ?? "";
}

<link href="~/Stylee/NewUsersStylee.css" rel="stylesheet" />

<div class="container" style="text-align: center; width: 100%; height: 100%">

    <div style="text-align: center; min-width: 100%">

        <style>
            .page-title {
                text-align: center;
                font-size: 21px;
                font-weight: 700;
                color: #2c3e50;
                margin-bottom: 15px;
            }

            .section-subtitle {
                text-align: center;
                font-size: 17px;
                font-weight: 500;
                color: #555;
                margin-bottom: 25px;
            }
        </style>

        <h2 class="page-title">Modificar estado del movimiento</h2>
        <h4 class="section-subtitle">Indica el nuevo estado que deseas asignar</h4>

        <hr>
        <div style=" display: flex; justify-content: center; align-items: center; height: auto;">
            <button class="animated-button" onclick="redirectBasedOnPage()">
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-2" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
                <span class="text">Return to back</span>
                <span class="circle"></span>
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-1" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
            </button>
        </div>
        <hr>

        @using (Html.BeginForm("NewConcept", "HISENSE", FormMethod.Post))
        {
            <input value="@ViewBag.ID" hidden="hidden" readonly="@true" id="id" name="id" />
            <input value="@ViewBag.Page" hidden="hidden" readonly="@true" id="Page" name="Page" />
            <input value="@ViewBag.data" hidden="hidden" readonly="@true" id="data" name="data" />

            <h5 class="Tittlelabel" style="font-weight: 700;">Marca el nivel de urgencia del movimiento:</h5>
            <div class="group">
                <select name="NivelUrgencia" id="NivelUrgencia" class="form-control" style="max-width: 30vh; color: black; text-align: center;">
                    <option value="Normal">Normal</option>
                    <option value="Urgente">Urgente</option>
                    <option value="Critico">Critico</option>
                </select>
            </div>

            <!-- Contenedor oculto por defecto y centrado -->
            <div id="MotivoUrgenciaContainer" style="margin-top: 15px; display: none; flex-direction: column; align-items: center;">
                <p for="MotivoUrgencia" style="font-weight: 600; margin-bottom: 5px;">Motivo de urgencia:</p>
                <input type="text" name="MotivoUrgencia" id="MotivoUrgencia" class="form-control"
                       placeholder="Describe el motivo..." style="max-width: 50vh; color: black; text-align: center;">
            </div>
            <br>

            <p style="text-align: center;">&nbsp;</p>
            <button type="submit" class="Bto_saved" style="width: 35vh">
                Guardar
            </button>
        }

    </div>

    </div>

<script>
    function toggleMotivoUrgencia() {
        const select = document.getElementById("NivelUrgencia");
        const motivoContainer = document.getElementById("MotivoUrgenciaContainer");
        const motivoInput = document.getElementById("MotivoUrgencia");

        const selectedValue = select.value.toLowerCase();

        if (selectedValue === "urgente" || selectedValue === "critico") {
            motivoContainer.style.display = "flex";
            motivoInput.value = ""; // Limpiar el valor si se cambia a urgente o crítico
        } else {
            motivoContainer.style.display = "none";
            motivoInput.value = "MOVIMIENTO NORMAL"; // Valor por defecto si es normal
        }
    }

    // Ejecutar al cargar la página
    window.addEventListener("DOMContentLoaded", toggleMotivoUrgencia);

    // Ejecutar cuando cambia el valor del select
    document.getElementById("NivelUrgencia").addEventListener("change", toggleMotivoUrgencia);
</script>

<script>
    function redirectBasedOnPage() {
        var page = "@pageValue".toLowerCase();
        var data = "@data".toString();
        if (page === "hisense" && data === "iNDEX") {
            window.location.href = '@Url.Action("EntryContainer", "RADA")';
        } else {
            if (page === "hisense" && data === "RADASers") {
                window.location.href = '@Url.Action("Records", "History")';
            } else {
                window.location.href = '@Url.Action("RequestContainer", "HISENSE")';
            }
        }
    }
</script>

RADALogisticsWEB/Views/HISENSE/Details.cshtml
@{
    ViewBag.Title = "RADA Logistics | Container Details";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://unpkg.com/lucide@latest"></script>

<link href="~/Stylee/DetailsStylees.css" rel="stylesheet" />

<input hidden="hidden" readonly="@true" value="@ViewBag.mot" />

<div class="container mt-5">

    @{
        string motValue = ViewBag.mot as string;

        string actionName;
        string controllerName;

        switch (motValue)
        {
            case "YES":
                actionName = "HRecord";
                controllerName = "History";
                break;
            case "RADASers":
                actionName = "Records";
                controllerName = "History";
                break;
            case "":
                actionName = "Records";
                controllerName = "History";
                break;
            case "CARGA":
                actionName = "RequestContainer";
                controllerName = "HISENSE";
                break;
            case "Cancellation":
                actionName = "Cancellation";
                controllerName = "Home";
                break;
            default:
                actionName = "HRecord";
                controllerName = "History";
                break;
        }

        var backUrl = Url.Action(actionName, controllerName);
    }



    <div class="d-flex justify-content-between align-items-center mb-4">

        <h2><i data-lucide="truck"></i> Detalles de contenedor</h2>
        <a href="@backUrl" class="btn btn-outline-secondary">
            <i data-lucide="arrow-left-circle"></i> Volver
        </a>

    </div>


    <div class="card shadow rounded-4 border-0 mb-4">
        <div class="card-body px-4 py-3">
            <div class="row g-3">

                <div class="col-md-6"><strong>Container:</strong> @ViewBag.Container | Placas: @ViewBag.Placa </div>

                <div class="col-md-6">

                    <strong>State:</strong>
                    @if (ViewBag.Status == "Entregado")
                    {
                        <span class="badge bg-success">Entregado</span>
                    }
                    else if (ViewBag.Status == "Pendiente")
                    {
                        <span class="badge bg-warning text-dark">Pendiente</span>
                    }
                    else
                    {
                        <span class="badge bg-secondary">@ViewBag.Status</span>
                    }

                </div>

                <div class="col-md-6"><strong>Hora de Solicitud:</strong> @ViewBag.Solicitud</div>

                <div class="col-md-6"><strong>Hora de Confirmacion:</strong> @ViewBag.Confirmacion</div>

                <div class="col-md-6"><strong>Hora de Entrega:</strong> @ViewBag.entrega</div>

                <div class="col-md-6"><strong>Chofer:</strong> @ViewBag.choffer</div>

                <div class="col-md-6"><strong>Origen:</strong> @ViewBag.origins</div>

                <div class="col-md-6"><strong>Destino:</strong> @ViewBag.destination</div>

                <div class="col-md-12"><strong>Motivo de Reporte Cancelado:</strong> @ViewBag.ReasonMT - @ViewBag.DateCancel </div>

                <div class="col-md-12"><strong>Estatus de Movimiento:</strong> @ViewBag.sts : @ViewBag.Desc | <a href="@Url.Action("ChangeStatus", "HISENSE" ,  new { ID = @ViewBag.ID, Page = "Hisense", data = @ViewBag.mot})" class="link-label"> ↻ Cambiar estado </a></div>

                <div class="col-md-6"><strong>Fecha de Solicitud:</strong> @ViewBag.date</div>

                <div class="col-md-6"><strong>Area:</strong> @ViewBag.Areas </div>

                <div class="col-md-6"><strong>Comentario:</strong> <span class="text-muted">@ViewBag.comment</span></div>

                <div class="col-md-6"><strong>Solicitado por:</strong> @ViewBag.Request</div>

                <button id="exportPDF" class="btn btn-danger mb-3">
                    <i data-lucide="download"></i> Exportar a PDF
                </button>

            </div>
        </div>
    </div>

    <p style="text-align: center;">&nbsp;</p>

    <h4 class="mb-3"><i data-lucide="list"></i> Historial de Movimientos </h4>
    <div class="table-scroll">
        <ul class="responsive-table">
            <li class="table-header" id="tableData">

                <div class="col col-10" style="font-size:13px">Número de Movimiento</div>

                <div class="col col-11" style="font-size:13px">Proceso Actual</div>

                <div class="col col-12" style="font-size:13px">Fecha de Finalización</div>

                <div class="col col-13" style="font-size:13px">Estado</div>

                <div class="col col-14" style="font-size:13px">Comentario</div>

                <div class="col col-15" style="font-size:13px">Fecha del Proceso</div>

            </li>

            @foreach (var person in ViewBag.Records)
            {
                <li class="table-row" id="tblCustomers" style="font-size: 12px; background-color: @(person.Status == "PENDIENTE" ? "#fff3cd" :

                  person.Status == "COMPLETADO" ? "#d1e7dd" : "white")">

                    <div class="col col-10" data-label="Movement Number" style="font-size:12px">@person.Folio</div>

                    <div class="col col-11" data-label="Current Process" style="font-size: 12px">@person.ProcessMovement</div>

                    <div class="col col-12" data-label="End Date" style="font-size: 12px">@person.End_date</div>

                    <div class="col col-13" data-label="Status" style="font-size: 12px">

                        <span style="font-size:13px" class="badge-status badge

                        @(person.Status == "PENDIENTE" ? "bg-warning text-dark" :
                          person.Status == "COMPLETADO" ? "bg-success" : "bg-secondary")">
                            @person.Status

                        </span>

                    </div>

                    <div class="col col-14" data-label="Comment" style="font-size:13px">@person.Comment</div>

                    <div class="col col-15" data-label="Date of Process" style="font-size:13px">@person.Date_Process</div>

                </li>
            }

        </ul>
    </div>

</div>

<script>
    lucide.createIcons();
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>

<script>
    var datenow = new Date().toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
    document.getElementById("exportPDF").addEventListener("click", function () {
        const container = document.querySelector(".container"); // todo lo que está dentro de tu vista

        html2canvas(container, { scale: 2 }).then(canvas => {
            const imgData = canvas.toDataURL("image/png");
            const { jsPDF } = window.jspdf;
            const pdf = new jsPDF('p', 'mm', 'a4');

            // Calcular el tamaño en el PDF
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            const imgWidth = pageWidth;
            const imgHeight = canvas.height * imgWidth / canvas.width;

            let position = 0;

            if (imgHeight < pageHeight) {
                pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
            } else {
                // Si la imagen es más alta que una página
                let heightLeft = imgHeight;
                while (heightLeft > 0) {
                    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                    heightLeft -= pageHeight;
                    if (heightLeft > 0) {
                        pdf.addPage();
                        position = 0;
                    }
                }
            }

            pdf.save("Container Details " + datenow + ".pdf");
        });
    });
</script>

RADALogisticsWEB/Views/HISENSE/table.cshtml
@{
    ViewBag.Title = "table";
}

<style>
    .urgencia-box {
        padding: 4px 10px;
        border-radius: 8px;
        font-weight: bold;
        display: inline-block;
        color: white;
        font-size: 0.9rem;
    }

    .urgencia-normal {
        background-color: #363F4A; /* gris */
        color: white;
    }

    .urgencia-urgente {
        background-color: #f5d142; /* amarillo */
        color: black;
    }

    .urgencia-critico {
        background-color: #D42401; /* naranja con rojo */
        color: white;
    }

</style>

@foreach (var person in ViewBag.Records)
{
<li class="table-row" id="tblCustomers" style="color:black ; background-color:
    @(person.message == "Canceled by Rada" ? "#E9B4B4" :
      person.message == "Canceled by Hisense" ? "#E9B4B4" :
      person.message == "PENDING" ? "#DDDCD4" :
      person.message == "CHOFER TERMINA MOVIMIENTO" ? "#C0E9B4" :
      person.message == "Movement in process" ? "#E5F8EC" : "#E9D8B4")">

    <div class="col col-6" data-label="Folio" style="text-align:center">
        <span class="urgencia-box @(person.Urgencia == "Normal" ? "urgencia-normal" : person.Urgencia == "Urgente" ? "urgencia-urgente" : person.Urgencia == "Critico" ? "urgencia-critico" : "")">
            @person.Urgencia
        </span>
    </div>

    <div class="col col-4" data-label="Folio" style="text-align:center">@person.Folio</div>

    @*<div class="col col-2" data-label="Username" style="text-align:center">@person.Who_Send</div>*@

    <div class="col col-4" data-label="Container" style="text-align:center"> @person.Container</div>

    <div class="col col-4" data-label="Destination Location" style="text-align:center"> @person.Destination_Location</div>

    <div class="col col-5" data-label="Origins Location" style="text-align:center"> @person.Origins_Location</div>

    <div class="col col-6" data-label="Status" style="text-align:center"> @person.Status</div>

    <div class="col col-2" data-label="Message" style="text-align:center"> @person.message</div>

    <div class="col col-6" data-label="Area" style="text-align:center"> @person.shift</div>

    <div class="col col-8" data-label="Date" style="text-align:center"> @person.Datetime</div>

    <div class="col col-4" data-label="Options" style="text-align:center">

        @*@Html.ActionLink("❌ Delete", "CancelContainer", new { ID = @person.Folio }) /*@
        @Html.ActionLink("🎴 Detalles", "Details", new { ID = @person.Folio, Record = "CARGA" })

    </div>
</li>
}