RADALogisticsWEB/Controllers/HistoryController.cs
using RADALogisticsWEB.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RADALogisticsWEB.Controllers
{
    public class HistoryController : Controller
    {
        List<Historial> GetRecords = new List<Historial>();

        List<Historial> GetRecordsDespachador = new List<Historial>();

        List<Historial> GetRecordsDespachadorExcle2 = new List<Historial>();

        List<Historial> GetRecordsExcel = new List<Historial>();

        List<Inventario> GetInventary = new List<Inventario>();

        List<Inventario> GetInventaryquery = new List<Inventario>();

        List<Historial> GetRecordsQeury = new List<Historial>();

        List<Historial> GetRecordsNow = new List<Historial>();

        List<Usuarios> GetChoffer = new List<Usuarios>();

        List<string> filtroAreas = new List<string>();

        List<UsuarioRada> UsuarioRadasss = new List<UsuarioRada>();

        //connection SQL server (database)
        SqlConnection DBSPP = new SqlConnection("Data Source=RADAEmpire.mssql.somee.com ;Initial Catalog=RADAEmpire ;User ID=RooRada; password=rada1311");
        SqlCommand con = new SqlCommand();
        SqlDataReader dr;
        // GET: History

        public ActionResult ChangesProcess(string ID, string ChofferOld, string Choffers)
        {
            // Intentar recuperar Username desde la cookie si está nulo
            if (Session["Username"] == null && Request.Cookies["UserCookie"] != null)
            {
                Session["Username"] = Request.Cookies["UserCookie"].Value;
            }

            // Intentar recuperar Type desde la cookie si está nulo
            if (Session["Type"] == null && Request.Cookies["TypeCookie"] != null)
            {
                Session["Type"] = Request.Cookies["TypeCookie"].Value;
            }

            // Validación final: si sigue sin Username o Type, redirigir al login
            if (Session["Username"] == null || Session["Type"] == null)
            {
                return RedirectToAction("LogIn", "Login");
            }
            else
            {
                ViewBag.User = Session["Username"];
            ViewBag.Type = Session["Type"];
                //create generate randoms int value
                string username = null, fastcard = null;
                SqlCommand asiggne = new SqlCommand("Select * from RADAEmpire_AChoffer where Active = '1' and Username = '" + Choffers + "'", DBSPP);
                DBSPP.Open();
                SqlDataReader drasiggne = asiggne.ExecuteReader();
                if (drasiggne.HasRows)
                {
                    while (drasiggne.Read())
                    {
                        username = drasiggne["Username"].ToString();
                        fastcard = drasiggne["Fastcard"].ToString();
                    }
                }
                DBSPP.Close();

                string updateQuery = "UPDATE RADAEmpire_CEntryContrainers SET Choffer = @Choffer, FastCard = @FastCard  WHERE Folio_Request = @ID";
                using (SqlCommand command = new SqlCommand(updateQuery, DBSPP))
                {
                    DBSPP.Open();
                    command.Parameters.AddWithValue("@Choffer", username.ToString());
                    command.Parameters.AddWithValue("@FastCard", fastcard.ToString());
                    command.Parameters.AddWithValue("@ID", ID);
                    int rowsAffected = command.ExecuteNonQuery();
                    DBSPP.Close();
                }

                string QUERY2 = "UPDATE RADAEmpires_DZChofferMovement SET Choffer = @Choffer,Message = @Message WHERE Foio = @ID";
                using (SqlCommand drqeuery = new SqlCommand(QUERY2, DBSPP))
                {
                    DBSPP.Open();
                    drqeuery.Parameters.AddWithValue("@Choffer", username.ToString());
                    drqeuery.Parameters.AddWithValue("@Message", "EL CHOFER " +  username.ToString() + " ESTA EN MOVIMIENTO");
                    drqeuery.Parameters.AddWithValue("@ID", ID);
                    int rowsAffected = drqeuery.ExecuteNonQuery();
                    DBSPP.Close();
                }

                string StatusChoffer = "UPDATE RADAEmpire_AChoffer SET Status = @Status WHERE Username = @ID";
                using (SqlCommand drqeuery = new SqlCommand(StatusChoffer, DBSPP))
                {
                    DBSPP.Open();
                    drqeuery.Parameters.AddWithValue("@Status", "SIN MOVIMIENTO");
                    drqeuery.Parameters.AddWithValue("@ID", ChofferOld.ToString());
                    int rowsAffected = drqeuery.ExecuteNonQuery();
                    DBSPP.Close();
                }

                string StatusChoffer2 = "UPDATE RADAEmpire_AChoffer SET Status = @Status WHERE Username = @ID";
                using (SqlCommand drqeuery = new SqlCommand(StatusChoffer2, DBSPP))
                {
                    DBSPP.Open();
                    drqeuery.Parameters.AddWithValue("@Status", "CHOFFER EN MOVIMIENTO");
                    drqeuery.Parameters.AddWithValue("@ID", username.ToString());
                    int rowsAffected = drqeuery.ExecuteNonQuery();
                    DBSPP.Close();
                }

                return RedirectToAction("EntryContainer", "RADA");
            }
        }

        public ActionResult ChangesCHR(string ID)
        {
            // Intentar recuperar Username desde la cookie si está nulo
            if (Session["Username"] == null && Request.Cookies["UserCookie"] != null)
            {
                Session["Username"] = Request.Cookies["UserCookie"].Value;
            }

            // Intentar recuperar Type desde la cookie si está nulo
            if (Session["Type"] == null && Request.Cookies["TypeCookie"] != null)
            {
                Session["Type"] = Request.Cookies["TypeCookie"].Value;
            }

            // Validación final: si sigue sin Username o Type, redirigir al login
            if (Session["Username"] == null || Session["Type"] == null)
            {
                return RedirectToAction("LogIn", "Login");
            }
            else
            { 
                ViewBag.User = Session["Username"];
            ViewBag.Type = Session["Type"];
                string UsuarioRada = Session["Username"]?.ToString();
                //create generate randoms int value
                string rol = null;
                SqlCommand asiggne = new SqlCommand("Select Type_user from RADAEmpire_AUsers where Active = '1' and Username = '" + UsuarioRada.ToString() + "'", DBSPP);
                DBSPP.Open();
                SqlDataReader drasiggne = asiggne.ExecuteReader();
                if (drasiggne.HasRows)
                {
                    while (drasiggne.Read())
                    {
                        rol = drasiggne["Type_user"].ToString();
                    }
                }
                DBSPP.Close();

                if (rol == "ADMINISTRATOR")
                {
                    GetUsers();
                    ViewBag.RadaUsers = GetChoffer;
                }
                else
                {
                    List<string> Areas = new List<string>();

                    // Paso 1: Obtener áreas del usuario
                    string queryAreas = "SELECT Areas FROM RADAEmpire_ARoles WHERE Active = '1' AND Username = @username";
                    using (SqlCommand RadaAreas = new SqlCommand(queryAreas, DBSPP))
                    {
                        RadaAreas.Parameters.AddWithValue("@username", UsuarioRada);
                        DBSPP.Open();
                        using (SqlDataReader drRadaAreas = RadaAreas.ExecuteReader())
                        {
                            while (drRadaAreas.Read())
                            {
                                Areas.Add(drRadaAreas["Areas"].ToString());
                            }
                        }
                        DBSPP.Close();
                    }

                    // Paso 2: Obtener usuarios por áreas
                    List<UsuarioRada> usuarios = new List<UsuarioRada>();

                    if (Areas.Any())
                    {
                        string queryUsers = "SELECT DISTINCT   r.Username,  r.Areas,  a.Status,  a.Fastcard, a.Shift, a.Date, a.Datetime " +
                            " FROM RADAEmpire_ARolesChoffer r LEFT JOIN RADAEmpire_AChoffer a  ON r.Username = a.Username AND a.Active = '1' " +
                            " WHERE r.Active = '1' AND r.Areas IN ({0}) AND (a.Status = 'SIN MOVIMIENTO' OR a.Status IS NULL)" +
                            " ORDER BY r.Username ASC";

                        List<string> parametros = new List<string>();
                        for (int i = 0; i < Areas.Count; i++)
                        {
                            parametros.Add("@area" + i);
                        }

                        string inClause = string.Join(", ", parametros);
                        queryUsers = string.Format(queryUsers, inClause);

                        using (SqlCommand cmd = new SqlCommand(queryUsers, DBSPP))
                        {
                            for (int i = 0; i < Areas.Count; i++)
                            {
                                cmd.Parameters.AddWithValue(parametros[i], Areas[i]);
                            }

                            DBSPP.Open();
                            using (SqlDataReader reader = cmd.ExecuteReader())
                            {
                                while (reader.Read())
                                {
                                    usuarios.Add(new UsuarioRada { Username = reader["Username"].ToString() });
                                }
                            }
                            DBSPP.Close();
                        }

RADALogisticsWEB/Views/History/CancelContainerH.cshtml
@{
    ViewBag.Title = "RADA Logistics | Remove";
}

<link href="~/Stylee/HisensePages.css" rel="stylesheet" />

<div class="container" style="text-align: center; width: 100%">

    <div style="text-align: center; min-width: 100%; ">

        <p style="text-align: center;">&nbsp;</p>
        <h4 class="labelTitt" style="font-size:24px"> ❌ Remove Container Movement </h4>
        <h5 style="text-align: center; font-size: 16px"> Enter the reason why you are removing the Movement </h5>

        <hr>
        <div style=" display: flex; justify-content: center; align-items: center; height: auto;">

            <button class="animated-button" onclick="location.href='@Url.Action("Records","History")'">
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-2" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
                <span class="text">Return to back</span>
                <span class="circle"></span>
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-1" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
            </button>

        </div>
        <hr>

       @using (Html.BeginForm("Delete", "History", FormMethod.Post))
        {
            <input id="ID" name="ID" value="@ViewBag.ID" hidden="hidden"  style="text-align:center" />
            <input id="Company" name="Company" value="HISENSE" hidden="hidden"  style="text-align:center" />

            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <div class="group">
                <input type="text" id="Reason" name="Reason" style=" font-size: 15px" required>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label>Reason Remove:</label>
            </div>

            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <button type="submit" class="Bto_saved">
                📍 Remove
            </button>
        }
    </div>

</div>

RADALogisticsWEB/Views/History/CancelContainerR.cshtml
@{
    ViewBag.Title = "RADA Logistics | Remove";
}

<link href="~/Stylee/HisensePages.css" rel="stylesheet" />

<div class="container" style="text-align: center; width: 100%">

    <div style="text-align: center; min-width: 100%; ">

        <p style="text-align: center;">&nbsp;</p>
        <h4 class="labelTitt" style="font-size:24px"> ❌ Cancelar movimiento de contenedor </h4>
        <h5 style="text-align: center; font-size: 16px"> Ingresa una razon / motivo por la cual el movimiento esta siendo cancelado </h5>

        <hr>
        <div style=" display: flex; justify-content: center; align-items: center; height: auto;">

            <button class="animated-button" onclick="location.href='@Url.Action("MoreOptions","RADA", new { ID = @ViewBag.ID})'">
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-2" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
                <span class="text">Return to back</span>
                <span class="circle"></span>
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-1" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
            </button>

        </div>
        <hr>

       @using (Html.BeginForm("Delete", "History", FormMethod.Post))
        {
            <input id="ID" name="ID" value="@ViewBag.ID" hidden="hidden" style="text-align:center" />
            <input id="Company" name="Company" value="RADA" hidden="hidden" style="text-align:center" />

            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <div class="group">
                <input type="text" id="Reason" name="Reason" style=" font-size: 15px" required>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label>Motivo / Razon:</label>
            </div>

            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <button type="submit" class="Bto_saved">
                Confirmar Movimiento
            </button>
        }
    </div>

</div>

RADALogisticsWEB/Views/History/ChangesCHR.cshtml
@{
    ViewBag.Title = "ChangesCHR";
}

<link href="~/Stylee/RecordsStylee.css" rel="stylesheet" />

<div class="container" style="text-align: center; width: 100%; height: 100%">

    <div style="text-align: center; min-width: 100%; ">

        <style>
            .page-title {
                text-align: center;
                font-size: 21px;
                font-weight: 700;
                color: #2c3e50;
                margin-bottom: 15px;
            }

            .section-subtitle {
                text-align: center;
                font-size: 17px;
                font-weight: 500;
                color: #555;
                margin-bottom: 25px;
            }
        </style>

        <h2 class="page-title"> Cambio de chofer para el movimiento </h2>
        <h4 class="section-subtitle"> Selecciona al nuevo chofer para terminar el movimiento </h4>

        <hr>
        <div style=" display: flex; justify-content: center; align-items: center; height: auto;">
            <button class="animated-button" onclick="location.href='@Url.Action("MoreOptions","RADA", new { ID = @ViewBag.ID,Comment = @ViewBag.Status })'">
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-2" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
                <span class="text">Return to back</span>
                <span class="circle"></span>
                <svg xmlns="http://www.w3.org/2000/svg" class="arr-1" viewBox="0 0 24 24">
                    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                </svg>
            </button>
        </div>
        <hr>


        @using (Html.BeginForm("ChangesProcess", "History", FormMethod.Post))
        {
            <p style="text-align: center;">&nbsp;</p>

            <input readonly="@true" type="text" id="ID" name="ID" value="@ViewBag.ID" hidden="hidden" required>

            <h5 class="Tittlelabel" style="font-weight: 700;"> Chofer Assignado en el movmiento Actual: </h5>
            <hr style="border: 1px solid #CECECE; width: 35vh; margin: 5px auto ">
            <p style="text-align: center;">&nbsp;</p>

            <div class="group">
                <input readonly="@true" type="text" id="ChofferOld" name="ChofferOld" value="@ViewBag.Choffer" required>
                <span class="highlight"></span>
                <span class="bar"></span>
            </div>

            <p style="text-align: center;">&nbsp;</p>

            <h5 class="Tittlelabel" style=" font-weight: 700; color: #5264AE"> Selecciona a un chofer:</h5>
            <div class="group" style="padding: 5px 0px 0px 0px">
                <select name="Choffers" id="Choffers" class="form-control" style="max-width: 40vh; color: black; text-align: center">
                    @foreach (var person in ViewBag.RadaUsers)
                    {
                        <option value="@person.Username">@person.Username</option>
                    }
                </select>
            </div>


            <!-- Campo oculto para enviar la decisión -->
            <input type="hidden" id="guardarAnterior" name="guardarAnterior" value="" />

            <p style="text-align: center;">&nbsp;</p>
            <button type="submit" class="Bto_saved">
                 Guardar Cambios
            </button>
            <p style="text-align: center;">&nbsp;</p>
        }


    </div>

</div>

RADALogisticsWEB/Views/History/HRecord.cshtml
@{
    ViewBag.Title = "RADA Logistics | Records";
}

<style>
    .urgencia-box {
        padding: 4px 10px;
        border-radius: 8px;
        font-weight: bold;
        display: inline-block;
        color: white;
        font-size: 0.9rem;
    }

    .urgencia-normal {
        background-color: #363F4A; /* gris */
        color: white;
    }

    .urgencia-urgente {
        background-color: #f5d142; /* amarillo */
        color: black;
    }

    .urgencia-critico {
        background-color: #D42401; /* naranja con rojo */
        color: white;
    }
</style>


@*<link href="~/Stylee/RecordsStylee.css" rel="stylesheet" />*@
<link href="~/Stylee/HisenseRecordsExcel.css" rel="stylesheet" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="~/Scripts/jquery.table2excel.min.js"></script>

<div class="container" style="text-align: center; width: 100%; height: 100%">

    <div style="text-align: center; min-width: 100%; ">

        <style>
            .page-title {
                text-align: center;
                font-size: 21px;
                font-weight: 700;
                color: #2c3e50;
                margin-bottom: 15px;
            }

            .section-subtitle {
                text-align: center;
                font-size: 17px;
                font-weight: 500;
                color: #555;
                margin-bottom: 25px;
            }
        </style>

        <h2 class="page-title">Historial de Movimiento de Contenedores - Consulta de Datos</h2>
        <h4 class="section-subtitle">Visualice la información de transacciones por rango de fechas</h4>

        @*<hr>
            <div style=" display: flex; justify-content: center; align-items: center; height: auto;">
                <button class="animated-button" onclick="location.href='@Url.Action("HisenseHome", "Home")'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="arr-2" viewBox="0 0 24 24">
                        <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                    </svg>
                    <span class="text">Return to back</span>
                    <span class="circle"></span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="arr-1" viewBox="0 0 24 24">
                        <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
                    </svg>
                </button>
            </div>
            <hr>*@

        @using (Html.BeginForm("HRecord", "History", FormMethod.Post))
        {
            <div class="form-row">

                <div class="form-group col-md-6 text-center">
                    <label for="TimeStart" style="font-family: 'Century Gothic'; display: block">Fecha Inicial:</label>
                    <input id="TimeStart" name="TimeStart" type="date" class="form-control mx-auto" style="max-width: 100%; display: block;" />
                </div>

                <div class="form-group col-md-6 text-center">
                    <label for="Timeend" style="font-family: 'Century Gothic'; display: block">Fecha Final:</label>
                    <input id="Timeend" name="Timeend" type="date" class="form-control mx-auto" style="max-width: 100%; display: block;" />
                </div>

                <p style="text-align: center;">&nbsp;</p>

                <button style="width:45vh" type="submit" class="Bto_saved">
                    Buscar
                </button>

                <p style="text-align: center;">&nbsp;</p>
            </div>
        }
    </div>
</div>

<p style="text-align: center;">&nbsp;</p>
<h4 style="text-align: center; font-weight: 700;" class="Tittlelabel"> Últimos registros ingresados en el sistema </h4>
<h5 style="text-align:center" class="Tittlelabel"> Total de Registros: @ViewBag.Count</h5>

<div class="table-scroll">
    <ul class="responsive-table">
        <li class="table-header" id="tableData">

            <div class="col col-1" style="text-align:center">Urgencia</div>

            <div class="col col-1" style="text-align:center">Folio</div>

            <div class="col col-2" style="text-align:center">Contenedor</div>

            <div class="col col-3" style="text-align:center">Origen</div>

            <div class="col col-4" style="text-align:center">Destino</div>

            <div class="col col-5" style="text-align:center">Estatus</div>

            <div class="col col-6" style="text-align:center">Solicitado</div>

            @*<div class="col col-6" style="text-align:center">HConfirm</div>

                <div class="col col-7" style="text-align:center">HFinish</div>*@

            <div class="col col-7" style="text-align:center">Solicitado por</div>

            <div class="col col-8" style="text-align:center">FastCard - Chofer</div>

            <div class="col col-9" style="text-align:center">Comentario</div>

            <div class="col col-10" style="text-align:center">Area</div>

            <div class="col col-10" style="text-align:center">Fecha</div>

            <div class="col col-11" style="text-align:center">Opciones</div>

        </li>
        @foreach (var person in ViewBag.Records)
        {
            <li class="table-row" id="tblCustomers" style="color:black ; background-color:
    @(person.Comment == "Canceled by Rada" ? "#E9B4B4" :
      person.Comment == "Canceled by Hisense" ? "#E9B4B4" :
      person.Comment == "PENDING" ? "#DDDCD4" :
      person.Comment == "CHOFER TERMINA MOVIMIENTO" ? "#C0E9B4" :
      person.Comment == "Movement in process" ? "#E5F8EC" : "#E9D8B4")">

                <div class="col col-1" data-label="Folio" style="text-align:center">
                    <span class="urgencia-box @(person.Urgencia == "Normal" ? "urgencia-normal" : person.Urgencia == "Urgente" ? "urgencia-urgente" : person.Urgencia == "Critico" ? "urgencia-critico" : "")">
                        @person.Urgencia
                    </span>
                </div>

                <div class="col col-1" data-label="Folio" style="text-align:center">@person.Folio</div>

                <div class="col col-2" data-label="Container" style="text-align:center">@person.Container</div>

                <div class="col col-3" data-label="Origins" style="text-align:center">@person.Origen</div>

                <div class="col col-4" data-label="Destination" style="text-align:center"> @person.Destination</div>

                <div class="col col-5" data-label="Status" style="text-align:center"> @person.Status</div>

                <div class="col col-6" data-label="HRequest" style="text-align:center"> @person.HSolicitud</div>

                @*<div class="col col-6" data-label="HConfirm" style="text-align:center"> @person.HConfirm</div>

                    <div class="col col-7" data-label="HFinish" style="text-align:center"> @person.HFinish</div>*@

                <div class="col col-7" data-label="Who Request" style="text-align:center"> @person.WhoRequest</div>

                <div class="col col-8" data-label="Choffer" style="text-align:center"> @person.fastcard</div>

                <div class="col col-9" data-label="Comment" style="text-align:center"> @person.Comment</div>

                <div class="col col-10" data-label="Date" style="text-align:center"> @person.Area</div>

                <div class="col col-10" data-label="Date" style="text-align:center"> @person.Date</div>

                <div class="col col-11" data-label="Options" style="text-align:center">

                    @*@Html.ActionLink("❌ Delete", "CancelContainer", new { ID = @person.Folio }) /*@
                    @*@Html.ActionLink("🎴 Details", "Details", "HISENSE" new { ID = @person.Folio })*@
                    @Html.ActionLink("🎴 Detalles", "Details", "Hisense", new { ID = person.Folio, Record = "YES" }, null)
                </div>

            </li>
        }
    </ul>
</div>

<table id="myTable" class="table2excel" class="table table-striped table-responsive-xl table-hover" hidden="hidden">
    <tr>

        <th style="text-align:center">
            <p> Container</p>
        </th>
        <th style="text-align:center">
            <p>
                Origins Loc
            </p>
        </th>
        <th style="text-align:center">
            <p>
                Destination Loc
            </p>
        </th>
        <th style="text-align:center">
            <p>Status</p>
        </th>
        <th style="text-align:center">
            <p>HRequest</p>
        </th>
        <th style="text-align:center">
            <p>
                Who Request
            </p>
        </th>
        <th style="text-align:center">
            <p>FastCard</p>
        </th>
        <th style="text-align:center">
            <p>Comment</p>
        </th>

        <th style="text-align:center">
            <p>Area</p>
        </th>

        <th style="text-align:center">
            <p>Date</p>
        </th>

    </tr>
    <tbody id="Table01">
        @foreach (var person in ViewBag.Records)
        {
            <tr>

                <td>
                    @person.Container
                </td>
                <td>
                    @person.Origen
                </td>
                <td>
                    @person.Destination
                </td>
                <td>
                    @person.Status
                </td>
                <td>
                    @person.HSolicitud
                </td>
                <td>
                    @person.WhoRequest
                </td>
                <td>
                    @person.fastcard
                </td>
                <td>
                    @person.Comment
                </td>
                <td>
                    @person.Area
                </td>

                <td>
                    @person.Date
                </td>
            </tr>
        }
    </tbody>
</table>

<p style="text-align: center;">&nbsp;</p>
<div style="text-align:center">
    <button id="Bton_Export" class="btn btn-success" style="text-align:left"> Exportar a excel <i class="fa fa-file-text"></i></button>
</div>
<p style="text-align: center;">&nbsp;</p>

<script>
    var datenow = new Date().toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
    // Function export grid to excel
    $("#Bton_Export").click(function () {
        $("#myTable").table2excel({
            name: "Backup file for HTML content",

            //  include extension also
            filename: "Control de Movimientos de Contenedores " + datenow + ".xls",

            // 'True' is set if background and font colors preserved
            preserveColors: false
        });
    });
</script>