RADALogisticsWEB/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RADALogisticsWEB.Controllers
{
    public class LoginController : Controller
    {
        //connection SQL server (database)
        SqlConnection DBSPP = new SqlConnection("Data Source=RADAEmpire.mssql.somee.com ;Initial Catalog=RADAEmpire ;User ID=RooRada; password=rada1311");
        SqlCommand con = new SqlCommand();
        SqlDataReader dr;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogIn()
        {
            ViewBag.message = "";
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string Username, string password)
        {
            if (Username != "" && password != "")
            {
                //query search username to employee enter to credentials
                string Usernames = null;
                SqlCommand sqlUsername = new SqlCommand("Select Username from RADAEmpire_AUsers where Active = '1' and Login_session = '" + Username + "'", DBSPP);
                DBSPP.Open();
                SqlDataReader drsqlUsername = sqlUsername.ExecuteReader();
                if (drsqlUsername.HasRows)
                {
                    while (drsqlUsername.Read())
                    {
                        Usernames = drsqlUsername[0].ToString();
                    }
                }
                else
                {
                    Usernames = null;
                }
                DBSPP.Close();

                if (Usernames == null)
                {
                    ViewBag.message = "Message: User no found !";
                    return View();
                }
                else
                {
                    //query search password to employee enter to credentials
                    string pass = null;
                    SqlCommand sqlPassword = new SqlCommand("Select Username from RADAEmpire_AUsers where Active = '1' and Login_session = '" + Username + "' and Password = '" + password + "'", DBSPP);
                    DBSPP.Open();
                    SqlDataReader drsqlPassword = sqlPassword.ExecuteReader();
                    if (drsqlPassword.HasRows)
                    {
                        while (drsqlPassword.Read())
                        {
                            pass = drsqlPassword[0].ToString();
                        }
                    }
                    else
                    {
                        pass = null;
                    }
                    DBSPP.Close();

                    if (pass == null)
                    {
                        ViewBag.message = "Message: User no found !";
                        return View();
                    }
                    else
                    {
                        string TypeLog = null;
                        SqlCommand log = new SqlCommand("Select Type_user from RADAEmpire_AUsers where Active = '1' and Login_session = '" + Username + "' and Password = '" + password + "'", DBSPP);
                        DBSPP.Open();
                        SqlDataReader drlog = log.ExecuteReader();
                        if (drlog.HasRows)
                        {
                            while (drlog.Read())
                            {
                                TypeLog = drlog[0].ToString();
                            }
                        }
                        DBSPP.Close();

                        // GUARDAR DATOS EN COOKIE (duración: 7 días)
                        HttpCookie userCookie = new HttpCookie("UserInfo");
                        userCookie["Username"] = Usernames;
                        userCookie["Rol"] = TypeLog;
                        userCookie.Expires = DateTime.Now.AddDays(7); // Puedes ajustar esto
                        Response.Cookies.Add(userCookie);

                        if (TypeLog == "ADMINISTRATOR")
                        {
                            //Go to next page (Menu Scroll)
                            //HomeController Frm = new HomeController();
                            //Frm.Username = Username;
                            Session["Username"] = Usernames;
                            Session["Type"] = TypeLog;
                            return RedirectToAction("AdministratorHome", "Home");
                        }
                        else
                        {
                            if (TypeLog == "HISENSE")
                            {
                                //Go to next page (Menu Scroll)
                                //HomeController Frm = new HomeController();
                                //Frm.Username = Username;
                                Session["Username"] = Usernames;
                                Session["Type"] = TypeLog;
                                return RedirectToAction("HisenseHome", "Home");
                            }
                            else
                            {
                                //View pages RADA
                                //Go to next page (Menu Scroll)
                                //HomeController Frm = new HomeController();
                                //Frm.Username = Username;
                                Session["Username"] = Usernames;
                                Session["Type"] = TypeLog;
                                return RedirectToAction("RadaHome", "Home");
                            }
                        }
                    }
                }
            }
            else
            {
                ViewBag.message = "Message: Error Credentials ! ";
                return View();
            }
        }
    }
}

RADALogisticsWEB/Views/Login/LogIn.cshtml
@{
    ViewBag.Title = "Log In";
}

<link href="~/Stylee/LogIn_StyleePage.css" rel="stylesheet" />

<div class="container">
    <div class="session" style="width:50vh; height:auto">
        <div class="left">
            <?xml version="1.0" encoding="UTF-8" ?>
            <svg enable-background="new 0 0 300 302.5" version="1.1" viewBox="0 0 300 302.5" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                
            <style type="text/css">
                .st01 {
                    fill: #fff;
                }
</style>

            <path class="st01" d="m126 302.2c-2.3 0.7-5.7 0.2-7.7-1.2l-105-71.6c-2-1.3-3.7-4.4-3.9-6.7l-9.4-126.7c-0.2-2.4 1.1-5.6 2.8-7.2l93.2-86.4c1.7-1.6 5.1-2.6 7.4-2.3l125.6 18.9c2.3 0.4 5.2 2.3 6.4 4.4l63.5 110.1c1.2 2 1.4 5.5 0.6 7.7l-46.4 118.3c-0.9 2.2-3.4 4.6-5.7 5.3l-121.4 37.4zm63.4-102.7c2.3-0.7 4.8-3.1 5.7-5.3l19.9-50.8c0.9-2.2 0.6-5.7-0.6-7.7l-27.3-47.3c-1.2-2-4.1-4-6.4-4.4l-53.9-8c-2.3-0.4-5.7 0.7-7.4 2.3l-40 37.1c-1.7 1.6-3 4.9-2.8 7.2l4.1 54.4c0.2 2.4 1.9 5.4 3.9 6.7l45.1 30.8c2 1.3 5.4 1.9 7.7 1.2l52-16.2z" />
            </svg>
        </div>

        @using (Html.BeginForm("LogIn", "Login", FormMethod.Post))
        {
            <form>
                <h5 style="color: #030826 ">RADA Logistics</h5>
                <p> ¡Bienvenido de nuevo! Ingrese sus credenciales para acceder al sistema: </p>

                <div class="floating-label">

                    @* INPUTS Username *@
                    <input placeholder="Usuario:" type="text" name="Username" id="Username" CssClass="uppercase" required=required />
                    <label for="Username">Usuario:</label>

                    <div class="icon">
                        <?xml version="1.0" encoding="UTF-8" ?>
                        <svg enable-background="new 0 0 100 100" version="1.1" viewBox="0 0 100 100" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                        
                        <style type="text/css">
                            .st0 {
                                fill: none;
                            }
</style>

                        <g transform="translate(0 -952.36)">
                        <path d="m17.5 977c-1.3 0-2.4 1.1-2.4 2.4v45.9c0 1.3 1.1 2.4 2.4 2.4h64.9c1.3 0 2.4-1.1 2.4-2.4v-45.9c0-1.3-1.1-2.4-2.4-2.4h-64.9zm2.4 4.8h60.2v1.2l-30.1 22-30.1-22v-1.2zm0 7l28.7 21c0.8 0.6 2 0.6 2.8 0l28.7-21v34.1h-60.2v-34.1z" />
                        </g>
                        <rect class="st0" width="100" height="100" />
                        </svg>
                    </div>

                </div>

                @* INPUTS password *@
                <div class="floating-label">
                    <input placeholder="Contraseña" type="password" name="password" id="password" required=required />
                    <label for="password">Contraseña:</label>
                    <div class="icon">
                        <?xml version="1.0" encoding="UTF-8" ?>
                        <svg enable-background="new 0 0 24 24" version="1.1" viewBox="0 0 24 24" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                        <style type="text/css">
                            .st0 {
                                fill: none;
                            }

                            .st1 {
                                fill: #010101;
                            }
</style>
                        <rect class="st0" width="24" height="24" />
                        <path class="st1" d="M19,21H5V9h14V21z M6,20h12V10H6V20z" />
                        <path class="st1" d="M16.5,10h-1V7c0-1.9-1.6-3.5-3.5-3.5S8.5,5.1,8.5,7v3h-1V7c0-2.5,2-4.5,4.5-4.5s4.5,2,4.5,4.5V10z" />
                        <path class="st1" d="m12 16.5c-0.8 0-1.5-0.7-1.5-1.5s0.7-1.5 1.5-1.5 1.5 0.7 1.5 1.5-0.7 1.5-1.5 1.5zm0-2c-0.3 0-0.5 0.2-0.5 0.5s0.2 0.5 0.5 0.5 0.5-0.2 0.5-0.5-0.2-0.5-0.5-0.5z" />
                        </svg>
                    </div>
                </div>

                <p style="text-align: center;">&nbsp;</p>
                <label style="color:red"> @ViewBag.message </label>
                <button type="submit">Iniciar Sesion</button>
            </form>
        }
    </div>
</div>